workspace = { members = []}
[package]
name = "leptos_samples"
version = "0.1.0"
authors = ["Jack Spagnoli"]
description = "Sample websites for Leptos"
readme = "README.md"
license = "MIT OR Apache-2.0"
