name: Build and store Site

on:
  workflow_call:
    inputs:
      DIRECTORY:
        type: string
        required: true
      UPLOAD:
        type: boolean
        required: false
        default: false

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
        with:
          asdf_branch: v0.11.3

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: make install
        run: |
          make install-build

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: install trunk
        run: cargo binstall -y trunk

      - name: build ${{ inputs.DIRECTORY }}
        run: |
          cd ${{ inputs.DIRECTORY }}
          trunk build --release

      - name: Upload dist directory
        if: ${{ inputs.UPLOAD }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ inputs.DIRECTORY }}
          path: ${{ inputs.DIRECTORY }}/dist