name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml
    with:
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

  pr_title_format_check:
    uses: ./.github/workflows/pr_title_check.yml
